### ISSUE TITLE
Disqus & Google Analytics ID

### ISSUE THREAD

**Issue by jakevdp** [jasminjohnson/jasminjohnson.github.io#1]
It looks like you're using the disqus and Google Analytics IDs from my site:

https://github.com/jasminjohnson/jasminjohnson.github.io/blob/src/publishconf.py#L23-L24

You should register your own so that you can track your own traffic, and so I don't get your notifications :smile:

**Comment by jasminjohnson** [comment]
ok - I updated.  thanks for your contribution and documentation - it's been so helpful for me.
Sorry for the inconvenience it may have caused.
